language: node_js
node_js: 
  - stable

cache:
  directories:
    - node_modules

env:
  - CI=true

install:
  - npm install
script: 
  - npm test

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -a $NETLIFY_ACCESS_TOKEN -d ./build --json --message "Travis-CI| [$TRAVIS_BRANCH:$TRAVIS_TAG] - $TRAVIS_COMMIT_MESSAGE" --prod
  skip_cleanup: true
  on:
    branch: master